export const GET_ESTADO_STARTED = 'GET_ESTADO_STARTED';
export const GET_ESTADO_SUCCESS = 'GET_ESTADO_SUCCESS';
export const GET_ESTADO_FAILURE = 'GET_ESTADO_FAILURE';

export const GET_MUNICIPIO_STARTED = 'GET_MUNICIPIO_STARTED';
export const GET_MUNICIPIO_SUCCESS = 'GET_MUNICIPIO_SUCCESS';
export const GET_MUNICIPIO_FAILURE = 'GET_MUNICIPIO_FAILURE';
